service: image-thumb-service
frameworkVersion: '3'	
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

plugins:
  - serverless-plugin-monorepo

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: portfolio-uploads
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
                - PUT
                - POST
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

functions:
  processCreatedObject:
    handler: index.handler
    events:
      - s3:
          bucket: portfolio-uploads
          event: s3:ObjectCreated:*
          existing: true