service: image-thumb-service
frameworkVersion: '3'	

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  stage: ${opt:stage,'dev'}
  environment:
    AWS_KEY: ${env:AWS_KEY}
    AWS_SECRET: ${env:AWS_SECRET}
    AWS_SECRET_SES: ${env:AWS_SECRET_SES}
    AWS_BUCKET: ${env:AWS_BUCKET}
    AWS_UPLOAD_BUCKET: ${env:AWS_UPLOAD_BUCKET}
    DATABASE_URL: ${env:DATABASE_URL} # Needed for the schema.prisma file
    PRISMA_QUERY_ENGINE_BINARY: 'node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node'
    PRISMA_QUERY_ENGINE_LIBRARY: 'node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node'

plugins:
  - serverless-esbuild
  - serverless-plugin-monorepo

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - 'src/schema.prisma'

custom:
  esbuild:
    bundle: true
    minify: false
    platform: "node"
    target: "es2020"
    concurrency: 10
    external:
      - sharp
    packagerOptions:
      scripts:
        - npm install --arch=x64 --platform=linux sharp

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: portfolio-uploads
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
                - PUT
                - POST
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

functions:
  processCreatedObject:
    handler: src/index.handler
    events:
      - s3:
          bucket: portfolio-uploads
          event: s3:ObjectCreated:*
          existing: true