service: image-thumb-service
frameworkVersion: '3'	
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  environment:
    AWS_KEY: ${env:AWS_KEY}
    AWS_SECRET: ${env:AWS_SECRET}
    AWS_SECRET_SES: ${env:AWS_SECRET_SES}
    AWS_BUCKET: ${env:AWS_BUCKET}
    AWS_UPLOAD_BUCKET: ${env:AWS_UPLOAD_BUCKET}

plugins:
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: portfolio-uploads
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
                - PUT
                - POST
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

functions:
  processCreatedObject:
    handler: dist/index.handler
    events:
      - s3:
          bucket: portfolio-uploads
          event: s3:ObjectCreated:*
          existing: true